services:
  - type: web
    name: selenium-api
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y wget unzip
      wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_96.0.4664.110-1_amd64.deb -O google-chrome.deb
      mkdir -p /opt/google/chrome
      dpkg-deb -xv google-chrome.deb /opt/google/chrome
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 app:app
