services:
  - type: web
    name: selenium-api
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y wget unzip
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dpkg -i google-chrome-stable_current_amd64.deb || apt-get -fy install
      apt-get install -y google-chrome-stable  # Ensure Chrome is installed properly
      which google-chrome  # Log where Chrome is installed to confirm
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 app:app
